### ISSUE TITLE
It should be more clear which step of the workflow was done

### ISSUE THREAD

**Issue by fosron** [remotecompany/slack-notification-action#1]
![Screenshot 2021-08-05 at 15 40 51](https://user-images.githubusercontent.com/3708631/128351650-8e9947e2-8be6-4780-87c3-0e72d1df6b60.png)

It was tests, then it was deployment, but you could not tell it from two identical messages.
Also i do think the `Mailersend - Completed` text is too big.

**Comment by robgordon89** [comment]
done please update action to @v1 version 

https://github.com/mailersend/mailersend/pull/2279

I will force push to this tag from now on, so we don't have to keep updating 👍
